version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456